/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/elessog/catkin_ws/src/matrice_from_imu/srv/matFromImu.srv
 *
 */


#ifndef MATRICE_FROM_IMU_MESSAGE_MATFROMIMU_H
#define MATRICE_FROM_IMU_MESSAGE_MATFROMIMU_H

#include <ros/service_traits.h>


#include <matrice_from_imu/matFromImuRequest.h>
#include <matrice_from_imu/matFromImuResponse.h>


namespace matrice_from_imu
{

struct matFromImu
{

typedef matFromImuRequest Request;
typedef matFromImuResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct matFromImu
} // namespace matrice_from_imu


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::matrice_from_imu::matFromImu > {
  static const char* value()
  {
    return "e3a7d6640adaaa61cc47ebadd8a9d365";
  }

  static const char* value(const ::matrice_from_imu::matFromImu&) { return value(); }
};

template<>
struct DataType< ::matrice_from_imu::matFromImu > {
  static const char* value()
  {
    return "matrice_from_imu/matFromImu";
  }

  static const char* value(const ::matrice_from_imu::matFromImu&) { return value(); }
};


// service_traits::MD5Sum< ::matrice_from_imu::matFromImuRequest> should match 
// service_traits::MD5Sum< ::matrice_from_imu::matFromImu > 
template<>
struct MD5Sum< ::matrice_from_imu::matFromImuRequest>
{
  static const char* value()
  {
    return MD5Sum< ::matrice_from_imu::matFromImu >::value();
  }
  static const char* value(const ::matrice_from_imu::matFromImuRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::matrice_from_imu::matFromImuRequest> should match 
// service_traits::DataType< ::matrice_from_imu::matFromImu > 
template<>
struct DataType< ::matrice_from_imu::matFromImuRequest>
{
  static const char* value()
  {
    return DataType< ::matrice_from_imu::matFromImu >::value();
  }
  static const char* value(const ::matrice_from_imu::matFromImuRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::matrice_from_imu::matFromImuResponse> should match 
// service_traits::MD5Sum< ::matrice_from_imu::matFromImu > 
template<>
struct MD5Sum< ::matrice_from_imu::matFromImuResponse>
{
  static const char* value()
  {
    return MD5Sum< ::matrice_from_imu::matFromImu >::value();
  }
  static const char* value(const ::matrice_from_imu::matFromImuResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::matrice_from_imu::matFromImuResponse> should match 
// service_traits::DataType< ::matrice_from_imu::matFromImu > 
template<>
struct DataType< ::matrice_from_imu::matFromImuResponse>
{
  static const char* value()
  {
    return DataType< ::matrice_from_imu::matFromImu >::value();
  }
  static const char* value(const ::matrice_from_imu::matFromImuResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MATRICE_FROM_IMU_MESSAGE_MATFROMIMU_H
